[package]
name = "netfilter_firewall_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnetwork = "0.20.0"
clap = { version = "3.2.20", features = ["yaml"] }